version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      # image: quay.io/keycloak/keycloak
      image: ghcr.io/tuananh/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # for testing, we disable hostname strict and enable http
        KC_HOSTNAME_STRICT: false
        KC_HTTP_ENABLED: true
        #JDBC_PARAMS: "ssl=true"
      command: ["start"]
      ports:
        - 8080:8080
      depends_on:
        - postgres
