package:
  name: keycloak
  version: "21.0.2"
  epoch: 0
  description:
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation:
      license: Apache-2.0
  dependencies:
    runtime:
      - bash # some helper scripts use bash
      - openjdk-17-jre

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - maven
      - openjdk-17
      - bash
      - nodejs-16
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/keycloak/keycloak
      tag: ${{package.version}}
      expected-commit: b9a56a7d3551b585a852c38beff92e9a99c30394
  - runs: |
      export LANG=en_US.UTF-8
      export JAVA_HOME=/usr/lib/jvm/openjdk

      mvn install -DskipTests=true -Dnode.version=$(node --version) -Pdistribution -q

      mkdir -p ${{targets.destdir}}/opt
      unzip -d ${{targets.destdir}}/opt quarkus/dist/target/keycloak-*.zip
      mv ${{targets.destdir}}/opt/keycloak-${{package.version}} ${{targets.destdir}}/opt/keycloak

      mkdir -p ${{targets.destdir}}/usr/bin
      for i in kc.sh kcadm.sh kcreg.sh; do
        ln -sf /opt/keycloak/bin/$i ${{targets.destdir}}/usr/bin/$i
      done

update:
  enabled: true
  github:
    identifier: keycloak/keycloak
    use-tag: true
    # There are a lot of older minor versions and tag schemes that make this flaky, restrict to just this major version
    tag-filter: "21."

advisories:
  CVE-2017-12158:
    - timestamp: 2023-04-09T09:54:02.778547-04:00
      status: not_affected
      justification: component_not_present
      impact: The CVE was fixed in a version of keycloak prior to our packaging
      fixed-version: "0"
    - timestamp: 2023-04-09T09:54:16.637324-04:00
      status: not_affected
      justification: vulnerable_code_not_in_execute_path
  CVE-2017-12159:
    - timestamp: 2023-04-09T09:53:42.563254-04:00
      status: not_affected
      justification: component_not_present
      impact: The CVE was fixed in a version of keycloak prior to our packaging
      fixed-version: "0"
    - timestamp: 2023-04-09T09:54:02.782617-04:00
      status: not_affected
      justification: vulnerable_code_not_in_execute_path

secfixes:
  "0":
    - CVE-2017-12159
    - CVE-2017-12158